export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';
export const ADD_CARD_FAILURE = 'ADD_CARD_FAILURE';
export const CURRENT_CARD = 'CURRENT_CARD';
export const RENDER_CARD = 'RENDER_CARD';
export const DELETE_CARD = 'DELETE_CARD'
